file_format: "1"
id: CRKBD
name: CORNE 
type: shield
url: https://github.com/benvallack/zmk-config-enki42
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - corne_left
  - corne_right
  - corne_dongle
